// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xendorser.proto

package com.baidu.xuper.pb;

public final class XendorserOuterClass {
    private XendorserOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface EndorserRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:pb.EndorserRequest)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        boolean hasHeader();

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        com.baidu.xuper.pb.XchainOuterClass.Header getHeader();

        /**
         * <pre>
         * 请求名(类型)
         * </pre>
         *
         * <code>optional string RequestName = 2;</code>
         */
        java.lang.String getRequestName();

        /**
         * <pre>
         * 请求名(类型)
         * </pre>
         *
         * <code>optional string RequestName = 2;</code>
         */
        com.google.protobuf.ByteString
        getRequestNameBytes();

        /**
         * <pre>
         * 请求链名
         * </pre>
         *
         * <code>optional string BcName = 3;</code>
         */
        java.lang.String getBcName();

        /**
         * <pre>
         * 请求链名
         * </pre>
         *
         * <code>optional string BcName = 3;</code>
         */
        com.google.protobuf.ByteString
        getBcNameBytes();

        /**
         * <pre>
         * 带签名的交易费Tx
         * </pre>
         *
         * <code>optional .pb.Transaction Fee = 4;</code>
         */
        boolean hasFee();

        /**
         * <pre>
         * 带签名的交易费Tx
         * </pre>
         *
         * <code>optional .pb.Transaction Fee = 4;</code>
         */
        com.baidu.xuper.pb.XchainOuterClass.Transaction getFee();

        /**
         * <pre>
         * Json打包的数据
         * </pre>
         *
         * <code>optional bytes RequestData = 5;</code>
         */
        com.google.protobuf.ByteString getRequestData();
    }

    /**
     * <pre>
     * 请求参数
     * </pre>
     * <p>
     * Protobuf type {@code pb.EndorserRequest}
     */
    public static final class EndorserRequest extends
            com.google.protobuf.GeneratedMessageLite<
                    EndorserRequest, EndorserRequest.Builder> implements
            // @@protoc_insertion_point(message_implements:pb.EndorserRequest)
            EndorserRequestOrBuilder {
        private EndorserRequest() {
            requestName_ = "";
            bcName_ = "";
            requestData_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static final int HEADER_FIELD_NUMBER = 1;
        private com.baidu.xuper.pb.XchainOuterClass.Header header_;

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        public boolean hasHeader() {
            return header_ != null;
        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        public com.baidu.xuper.pb.XchainOuterClass.Header getHeader() {
            return header_ == null ? com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        private void setHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
            if (value == null) {
                throw new NullPointerException();
            }
            header_ = value;

        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        private void setHeader(
                com.baidu.xuper.pb.XchainOuterClass.Header.Builder builderForValue) {
            header_ = builderForValue.build();

        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        private void mergeHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
            if (header_ != null &&
                    header_ != com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance()) {
                header_ =
                        com.baidu.xuper.pb.XchainOuterClass.Header.newBuilder(header_).mergeFrom(value).buildPartial();
            } else {
                header_ = value;
            }

        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        private void clearHeader() {
            header_ = null;

        }

        public static final int REQUESTNAME_FIELD_NUMBER = 2;
        private java.lang.String requestName_;

        /**
         * <pre>
         * 请求名(类型)
         * </pre>
         *
         * <code>optional string RequestName = 2;</code>
         */
        public java.lang.String getRequestName() {
            return requestName_;
        }

        /**
         * <pre>
         * 请求名(类型)
         * </pre>
         *
         * <code>optional string RequestName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getRequestNameBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(requestName_);
        }

        /**
         * <pre>
         * 请求名(类型)
         * </pre>
         *
         * <code>optional string RequestName = 2;</code>
         */
        private void setRequestName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            requestName_ = value;
        }

        /**
         * <pre>
         * 请求名(类型)
         * </pre>
         *
         * <code>optional string RequestName = 2;</code>
         */
        private void clearRequestName() {

            requestName_ = getDefaultInstance().getRequestName();
        }

        /**
         * <pre>
         * 请求名(类型)
         * </pre>
         *
         * <code>optional string RequestName = 2;</code>
         */
        private void setRequestNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            requestName_ = value.toStringUtf8();
        }

        public static final int BCNAME_FIELD_NUMBER = 3;
        private java.lang.String bcName_;

        /**
         * <pre>
         * 请求链名
         * </pre>
         *
         * <code>optional string BcName = 3;</code>
         */
        public java.lang.String getBcName() {
            return bcName_;
        }

        /**
         * <pre>
         * 请求链名
         * </pre>
         *
         * <code>optional string BcName = 3;</code>
         */
        public com.google.protobuf.ByteString
        getBcNameBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(bcName_);
        }

        /**
         * <pre>
         * 请求链名
         * </pre>
         *
         * <code>optional string BcName = 3;</code>
         */
        private void setBcName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            bcName_ = value;
        }

        /**
         * <pre>
         * 请求链名
         * </pre>
         *
         * <code>optional string BcName = 3;</code>
         */
        private void clearBcName() {

            bcName_ = getDefaultInstance().getBcName();
        }

        /**
         * <pre>
         * 请求链名
         * </pre>
         *
         * <code>optional string BcName = 3;</code>
         */
        private void setBcNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            bcName_ = value.toStringUtf8();
        }

        public static final int FEE_FIELD_NUMBER = 4;
        private com.baidu.xuper.pb.XchainOuterClass.Transaction fee_;

        /**
         * <pre>
         * 带签名的交易费Tx
         * </pre>
         *
         * <code>optional .pb.Transaction Fee = 4;</code>
         */
        public boolean hasFee() {
            return fee_ != null;
        }

        /**
         * <pre>
         * 带签名的交易费Tx
         * </pre>
         *
         * <code>optional .pb.Transaction Fee = 4;</code>
         */
        public com.baidu.xuper.pb.XchainOuterClass.Transaction getFee() {
            return fee_ == null ? com.baidu.xuper.pb.XchainOuterClass.Transaction.getDefaultInstance() : fee_;
        }

        /**
         * <pre>
         * 带签名的交易费Tx
         * </pre>
         *
         * <code>optional .pb.Transaction Fee = 4;</code>
         */
        private void setFee(com.baidu.xuper.pb.XchainOuterClass.Transaction value) {
            if (value == null) {
                throw new NullPointerException();
            }
            fee_ = value;

        }

        /**
         * <pre>
         * 带签名的交易费Tx
         * </pre>
         *
         * <code>optional .pb.Transaction Fee = 4;</code>
         */
        private void setFee(
                com.baidu.xuper.pb.XchainOuterClass.Transaction.Builder builderForValue) {
            fee_ = builderForValue.build();

        }

        /**
         * <pre>
         * 带签名的交易费Tx
         * </pre>
         *
         * <code>optional .pb.Transaction Fee = 4;</code>
         */
        private void mergeFee(com.baidu.xuper.pb.XchainOuterClass.Transaction value) {
            if (fee_ != null &&
                    fee_ != com.baidu.xuper.pb.XchainOuterClass.Transaction.getDefaultInstance()) {
                fee_ =
                        com.baidu.xuper.pb.XchainOuterClass.Transaction.newBuilder(fee_).mergeFrom(value).buildPartial();
            } else {
                fee_ = value;
            }

        }

        /**
         * <pre>
         * 带签名的交易费Tx
         * </pre>
         *
         * <code>optional .pb.Transaction Fee = 4;</code>
         */
        private void clearFee() {
            fee_ = null;

        }

        public static final int REQUESTDATA_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString requestData_;

        /**
         * <pre>
         * Json打包的数据
         * </pre>
         *
         * <code>optional bytes RequestData = 5;</code>
         */
        public com.google.protobuf.ByteString getRequestData() {
            return requestData_;
        }

        /**
         * <pre>
         * Json打包的数据
         * </pre>
         *
         * <code>optional bytes RequestData = 5;</code>
         */
        private void setRequestData(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            requestData_ = value;
        }

        /**
         * <pre>
         * Json打包的数据
         * </pre>
         *
         * <code>optional bytes RequestData = 5;</code>
         */
        private void clearRequestData() {

            requestData_ = getDefaultInstance().getRequestData();
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (header_ != null) {
                output.writeMessage(1, getHeader());
            }
            if (!requestName_.isEmpty()) {
                output.writeString(2, getRequestName());
            }
            if (!bcName_.isEmpty()) {
                output.writeString(3, getBcName());
            }
            if (fee_ != null) {
                output.writeMessage(4, getFee());
            }
            if (!requestData_.isEmpty()) {
                output.writeBytes(5, requestData_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (header_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getHeader());
            }
            if (!requestName_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(2, getRequestName());
            }
            if (!bcName_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(3, getBcName());
            }
            if (fee_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, getFee());
            }
            if (!requestData_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, requestData_);
            }
            memoizedSerializedSize = size;
            return size;
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * <pre>
         * 请求参数
         * </pre>
         * <p>
         * Protobuf type {@code pb.EndorserRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest, Builder> implements
                // @@protoc_insertion_point(builder_implements:pb.EndorserRequest)
                com.baidu.xuper.pb.XendorserOuterClass.EndorserRequestOrBuilder {
            // Construct using com.baidu.xuperunion.pb.XendorserOuterClass.EndorserRequest.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public boolean hasHeader() {
                return instance.hasHeader();
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public com.baidu.xuper.pb.XchainOuterClass.Header getHeader() {
                return instance.getHeader();
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public Builder setHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
                copyOnWrite();
                instance.setHeader(value);
                return this;
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public Builder setHeader(
                    com.baidu.xuper.pb.XchainOuterClass.Header.Builder builderForValue) {
                copyOnWrite();
                instance.setHeader(builderForValue);
                return this;
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public Builder mergeHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
                copyOnWrite();
                instance.mergeHeader(value);
                return this;
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public Builder clearHeader() {
                copyOnWrite();
                instance.clearHeader();
                return this;
            }

            /**
             * <pre>
             * 请求名(类型)
             * </pre>
             *
             * <code>optional string RequestName = 2;</code>
             */
            public java.lang.String getRequestName() {
                return instance.getRequestName();
            }

            /**
             * <pre>
             * 请求名(类型)
             * </pre>
             *
             * <code>optional string RequestName = 2;</code>
             */
            public com.google.protobuf.ByteString
            getRequestNameBytes() {
                return instance.getRequestNameBytes();
            }

            /**
             * <pre>
             * 请求名(类型)
             * </pre>
             *
             * <code>optional string RequestName = 2;</code>
             */
            public Builder setRequestName(
                    java.lang.String value) {
                copyOnWrite();
                instance.setRequestName(value);
                return this;
            }

            /**
             * <pre>
             * 请求名(类型)
             * </pre>
             *
             * <code>optional string RequestName = 2;</code>
             */
            public Builder clearRequestName() {
                copyOnWrite();
                instance.clearRequestName();
                return this;
            }

            /**
             * <pre>
             * 请求名(类型)
             * </pre>
             *
             * <code>optional string RequestName = 2;</code>
             */
            public Builder setRequestNameBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setRequestNameBytes(value);
                return this;
            }

            /**
             * <pre>
             * 请求链名
             * </pre>
             *
             * <code>optional string BcName = 3;</code>
             */
            public java.lang.String getBcName() {
                return instance.getBcName();
            }

            /**
             * <pre>
             * 请求链名
             * </pre>
             *
             * <code>optional string BcName = 3;</code>
             */
            public com.google.protobuf.ByteString
            getBcNameBytes() {
                return instance.getBcNameBytes();
            }

            /**
             * <pre>
             * 请求链名
             * </pre>
             *
             * <code>optional string BcName = 3;</code>
             */
            public Builder setBcName(
                    java.lang.String value) {
                copyOnWrite();
                instance.setBcName(value);
                return this;
            }

            /**
             * <pre>
             * 请求链名
             * </pre>
             *
             * <code>optional string BcName = 3;</code>
             */
            public Builder clearBcName() {
                copyOnWrite();
                instance.clearBcName();
                return this;
            }

            /**
             * <pre>
             * 请求链名
             * </pre>
             *
             * <code>optional string BcName = 3;</code>
             */
            public Builder setBcNameBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setBcNameBytes(value);
                return this;
            }

            /**
             * <pre>
             * 带签名的交易费Tx
             * </pre>
             *
             * <code>optional .pb.Transaction Fee = 4;</code>
             */
            public boolean hasFee() {
                return instance.hasFee();
            }

            /**
             * <pre>
             * 带签名的交易费Tx
             * </pre>
             *
             * <code>optional .pb.Transaction Fee = 4;</code>
             */
            public com.baidu.xuper.pb.XchainOuterClass.Transaction getFee() {
                return instance.getFee();
            }

            /**
             * <pre>
             * 带签名的交易费Tx
             * </pre>
             *
             * <code>optional .pb.Transaction Fee = 4;</code>
             */
            public Builder setFee(com.baidu.xuper.pb.XchainOuterClass.Transaction value) {
                copyOnWrite();
                instance.setFee(value);
                return this;
            }

            /**
             * <pre>
             * 带签名的交易费Tx
             * </pre>
             *
             * <code>optional .pb.Transaction Fee = 4;</code>
             */
            public Builder setFee(
                    com.baidu.xuper.pb.XchainOuterClass.Transaction.Builder builderForValue) {
                copyOnWrite();
                instance.setFee(builderForValue);
                return this;
            }

            /**
             * <pre>
             * 带签名的交易费Tx
             * </pre>
             *
             * <code>optional .pb.Transaction Fee = 4;</code>
             */
            public Builder mergeFee(com.baidu.xuper.pb.XchainOuterClass.Transaction value) {
                copyOnWrite();
                instance.mergeFee(value);
                return this;
            }

            /**
             * <pre>
             * 带签名的交易费Tx
             * </pre>
             *
             * <code>optional .pb.Transaction Fee = 4;</code>
             */
            public Builder clearFee() {
                copyOnWrite();
                instance.clearFee();
                return this;
            }

            /**
             * <pre>
             * Json打包的数据
             * </pre>
             *
             * <code>optional bytes RequestData = 5;</code>
             */
            public com.google.protobuf.ByteString getRequestData() {
                return instance.getRequestData();
            }

            /**
             * <pre>
             * Json打包的数据
             * </pre>
             *
             * <code>optional bytes RequestData = 5;</code>
             */
            public Builder setRequestData(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setRequestData(value);
                return this;
            }

            /**
             * <pre>
             * Json打包的数据
             * </pre>
             *
             * <code>optional bytes RequestData = 5;</code>
             */
            public Builder clearRequestData() {
                copyOnWrite();
                instance.clearRequestData();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:pb.EndorserRequest)
        }

        protected final Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest other = (com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest) arg1;
                    header_ = visitor.visitMessage(header_, other.header_);
                    requestName_ = visitor.visitString(!requestName_.isEmpty(), requestName_,
                            !other.requestName_.isEmpty(), other.requestName_);
                    bcName_ = visitor.visitString(!bcName_.isEmpty(), bcName_,
                            !other.bcName_.isEmpty(), other.bcName_);
                    fee_ = visitor.visitMessage(fee_, other.fee_);
                    requestData_ = visitor.visitByteString(requestData_ != com.google.protobuf.ByteString.EMPTY, requestData_,
                            other.requestData_ != com.google.protobuf.ByteString.EMPTY, other.requestData_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                            .INSTANCE) {
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!input.skipField(tag)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 10: {
                                    com.baidu.xuper.pb.XchainOuterClass.Header.Builder subBuilder = null;
                                    if (header_ != null) {
                                        subBuilder = header_.toBuilder();
                                    }
                                    header_ = input.readMessage(com.baidu.xuper.pb.XchainOuterClass.Header.parser(), extensionRegistry);
                                    if (subBuilder != null) {
                                        subBuilder.mergeFrom(header_);
                                        header_ = subBuilder.buildPartial();
                                    }

                                    break;
                                }
                                case 18: {
                                    String s = input.readStringRequireUtf8();

                                    requestName_ = s;
                                    break;
                                }
                                case 26: {
                                    String s = input.readStringRequireUtf8();

                                    bcName_ = s;
                                    break;
                                }
                                case 34: {
                                    com.baidu.xuper.pb.XchainOuterClass.Transaction.Builder subBuilder = null;
                                    if (fee_ != null) {
                                        subBuilder = fee_.toBuilder();
                                    }
                                    fee_ = input.readMessage(com.baidu.xuper.pb.XchainOuterClass.Transaction.parser(), extensionRegistry);
                                    if (subBuilder != null) {
                                        subBuilder.mergeFrom(fee_);
                                        fee_ = subBuilder.buildPartial();
                                    }

                                    break;
                                }
                                case 42: {

                                    requestData_ = input.readBytes();
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {
                        synchronized (com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest.class) {
                            if (PARSER == null) {
                                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                            }
                        }
                    }
                    return PARSER;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:pb.EndorserRequest)
        private static final com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new EndorserRequest();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<EndorserRequest> PARSER;

        public static com.google.protobuf.Parser<EndorserRequest> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface EndorserResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:pb.EndorserResponse)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        boolean hasHeader();

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        com.baidu.xuper.pb.XchainOuterClass.Header getHeader();

        /**
         * <code>optional string ResponseName = 2;</code>
         */
        java.lang.String getResponseName();

        /**
         * <code>optional string ResponseName = 2;</code>
         */
        com.google.protobuf.ByteString
        getResponseNameBytes();

        /**
         * <pre>
         * 背书服务地址
         * </pre>
         *
         * <code>optional string EndorserAddress = 3;</code>
         */
        java.lang.String getEndorserAddress();

        /**
         * <pre>
         * 背书服务地址
         * </pre>
         *
         * <code>optional string EndorserAddress = 3;</code>
         */
        com.google.protobuf.ByteString
        getEndorserAddressBytes();

        /**
         * <pre>
         * 背书服务签名
         * </pre>
         *
         * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
         */
        boolean hasEndorserSign();

        /**
         * <pre>
         * 背书服务签名
         * </pre>
         *
         * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
         */
        com.baidu.xuper.pb.XchainOuterClass.SignatureInfo getEndorserSign();

        /**
         * <code>optional bytes ResponseData = 5;</code>
         */
        com.google.protobuf.ByteString getResponseData();
    }

    /**
     * Protobuf type {@code pb.EndorserResponse}
     */
    public static final class EndorserResponse extends
            com.google.protobuf.GeneratedMessageLite<
                    EndorserResponse, EndorserResponse.Builder> implements
            // @@protoc_insertion_point(message_implements:pb.EndorserResponse)
            EndorserResponseOrBuilder {
        private EndorserResponse() {
            responseName_ = "";
            endorserAddress_ = "";
            responseData_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static final int HEADER_FIELD_NUMBER = 1;
        private com.baidu.xuper.pb.XchainOuterClass.Header header_;

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        public boolean hasHeader() {
            return header_ != null;
        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        public com.baidu.xuper.pb.XchainOuterClass.Header getHeader() {
            return header_ == null ? com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance() : header_;
        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        private void setHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
            if (value == null) {
                throw new NullPointerException();
            }
            header_ = value;

        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        private void setHeader(
                com.baidu.xuper.pb.XchainOuterClass.Header.Builder builderForValue) {
            header_ = builderForValue.build();

        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        private void mergeHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
            if (header_ != null &&
                    header_ != com.baidu.xuper.pb.XchainOuterClass.Header.getDefaultInstance()) {
                header_ =
                        com.baidu.xuper.pb.XchainOuterClass.Header.newBuilder(header_).mergeFrom(value).buildPartial();
            } else {
                header_ = value;
            }

        }

        /**
         * <code>optional .pb.Header header = 1;</code>
         */
        private void clearHeader() {
            header_ = null;

        }

        public static final int RESPONSENAME_FIELD_NUMBER = 2;
        private java.lang.String responseName_;

        /**
         * <code>optional string ResponseName = 2;</code>
         */
        public java.lang.String getResponseName() {
            return responseName_;
        }

        /**
         * <code>optional string ResponseName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getResponseNameBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(responseName_);
        }

        /**
         * <code>optional string ResponseName = 2;</code>
         */
        private void setResponseName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            responseName_ = value;
        }

        /**
         * <code>optional string ResponseName = 2;</code>
         */
        private void clearResponseName() {

            responseName_ = getDefaultInstance().getResponseName();
        }

        /**
         * <code>optional string ResponseName = 2;</code>
         */
        private void setResponseNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            responseName_ = value.toStringUtf8();
        }

        public static final int ENDORSERADDRESS_FIELD_NUMBER = 3;
        private java.lang.String endorserAddress_;

        /**
         * <pre>
         * 背书服务地址
         * </pre>
         *
         * <code>optional string EndorserAddress = 3;</code>
         */
        public java.lang.String getEndorserAddress() {
            return endorserAddress_;
        }

        /**
         * <pre>
         * 背书服务地址
         * </pre>
         *
         * <code>optional string EndorserAddress = 3;</code>
         */
        public com.google.protobuf.ByteString
        getEndorserAddressBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(endorserAddress_);
        }

        /**
         * <pre>
         * 背书服务地址
         * </pre>
         *
         * <code>optional string EndorserAddress = 3;</code>
         */
        private void setEndorserAddress(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            endorserAddress_ = value;
        }

        /**
         * <pre>
         * 背书服务地址
         * </pre>
         *
         * <code>optional string EndorserAddress = 3;</code>
         */
        private void clearEndorserAddress() {

            endorserAddress_ = getDefaultInstance().getEndorserAddress();
        }

        /**
         * <pre>
         * 背书服务地址
         * </pre>
         *
         * <code>optional string EndorserAddress = 3;</code>
         */
        private void setEndorserAddressBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            endorserAddress_ = value.toStringUtf8();
        }

        public static final int ENDORSERSIGN_FIELD_NUMBER = 4;
        private com.baidu.xuper.pb.XchainOuterClass.SignatureInfo endorserSign_;

        /**
         * <pre>
         * 背书服务签名
         * </pre>
         *
         * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
         */
        public boolean hasEndorserSign() {
            return endorserSign_ != null;
        }

        /**
         * <pre>
         * 背书服务签名
         * </pre>
         *
         * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
         */
        public com.baidu.xuper.pb.XchainOuterClass.SignatureInfo getEndorserSign() {
            return endorserSign_ == null ? com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.getDefaultInstance() : endorserSign_;
        }

        /**
         * <pre>
         * 背书服务签名
         * </pre>
         *
         * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
         */
        private void setEndorserSign(com.baidu.xuper.pb.XchainOuterClass.SignatureInfo value) {
            if (value == null) {
                throw new NullPointerException();
            }
            endorserSign_ = value;

        }

        /**
         * <pre>
         * 背书服务签名
         * </pre>
         *
         * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
         */
        private void setEndorserSign(
                com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.Builder builderForValue) {
            endorserSign_ = builderForValue.build();

        }

        /**
         * <pre>
         * 背书服务签名
         * </pre>
         *
         * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
         */
        private void mergeEndorserSign(com.baidu.xuper.pb.XchainOuterClass.SignatureInfo value) {
            if (endorserSign_ != null &&
                    endorserSign_ != com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.getDefaultInstance()) {
                endorserSign_ =
                        com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.newBuilder(endorserSign_).mergeFrom(value).buildPartial();
            } else {
                endorserSign_ = value;
            }

        }

        /**
         * <pre>
         * 背书服务签名
         * </pre>
         *
         * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
         */
        private void clearEndorserSign() {
            endorserSign_ = null;

        }

        public static final int RESPONSEDATA_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString responseData_;

        /**
         * <code>optional bytes ResponseData = 5;</code>
         */
        public com.google.protobuf.ByteString getResponseData() {
            return responseData_;
        }

        /**
         * <code>optional bytes ResponseData = 5;</code>
         */
        private void setResponseData(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            responseData_ = value;
        }

        /**
         * <code>optional bytes ResponseData = 5;</code>
         */
        private void clearResponseData() {

            responseData_ = getDefaultInstance().getResponseData();
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (header_ != null) {
                output.writeMessage(1, getHeader());
            }
            if (!responseName_.isEmpty()) {
                output.writeString(2, getResponseName());
            }
            if (!endorserAddress_.isEmpty()) {
                output.writeString(3, getEndorserAddress());
            }
            if (endorserSign_ != null) {
                output.writeMessage(4, getEndorserSign());
            }
            if (!responseData_.isEmpty()) {
                output.writeBytes(5, responseData_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (header_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getHeader());
            }
            if (!responseName_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(2, getResponseName());
            }
            if (!endorserAddress_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(3, getEndorserAddress());
            }
            if (endorserSign_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, getEndorserSign());
            }
            if (!responseData_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, responseData_);
            }
            memoizedSerializedSize = size;
            return size;
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * Protobuf type {@code pb.EndorserResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse, Builder> implements
                // @@protoc_insertion_point(builder_implements:pb.EndorserResponse)
                com.baidu.xuper.pb.XendorserOuterClass.EndorserResponseOrBuilder {
            // Construct using com.baidu.xuperunion.pb.XendorserOuterClass.EndorserResponse.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public boolean hasHeader() {
                return instance.hasHeader();
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public com.baidu.xuper.pb.XchainOuterClass.Header getHeader() {
                return instance.getHeader();
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public Builder setHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
                copyOnWrite();
                instance.setHeader(value);
                return this;
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public Builder setHeader(
                    com.baidu.xuper.pb.XchainOuterClass.Header.Builder builderForValue) {
                copyOnWrite();
                instance.setHeader(builderForValue);
                return this;
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public Builder mergeHeader(com.baidu.xuper.pb.XchainOuterClass.Header value) {
                copyOnWrite();
                instance.mergeHeader(value);
                return this;
            }

            /**
             * <code>optional .pb.Header header = 1;</code>
             */
            public Builder clearHeader() {
                copyOnWrite();
                instance.clearHeader();
                return this;
            }

            /**
             * <code>optional string ResponseName = 2;</code>
             */
            public java.lang.String getResponseName() {
                return instance.getResponseName();
            }

            /**
             * <code>optional string ResponseName = 2;</code>
             */
            public com.google.protobuf.ByteString
            getResponseNameBytes() {
                return instance.getResponseNameBytes();
            }

            /**
             * <code>optional string ResponseName = 2;</code>
             */
            public Builder setResponseName(
                    java.lang.String value) {
                copyOnWrite();
                instance.setResponseName(value);
                return this;
            }

            /**
             * <code>optional string ResponseName = 2;</code>
             */
            public Builder clearResponseName() {
                copyOnWrite();
                instance.clearResponseName();
                return this;
            }

            /**
             * <code>optional string ResponseName = 2;</code>
             */
            public Builder setResponseNameBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setResponseNameBytes(value);
                return this;
            }

            /**
             * <pre>
             * 背书服务地址
             * </pre>
             *
             * <code>optional string EndorserAddress = 3;</code>
             */
            public java.lang.String getEndorserAddress() {
                return instance.getEndorserAddress();
            }

            /**
             * <pre>
             * 背书服务地址
             * </pre>
             *
             * <code>optional string EndorserAddress = 3;</code>
             */
            public com.google.protobuf.ByteString
            getEndorserAddressBytes() {
                return instance.getEndorserAddressBytes();
            }

            /**
             * <pre>
             * 背书服务地址
             * </pre>
             *
             * <code>optional string EndorserAddress = 3;</code>
             */
            public Builder setEndorserAddress(
                    java.lang.String value) {
                copyOnWrite();
                instance.setEndorserAddress(value);
                return this;
            }

            /**
             * <pre>
             * 背书服务地址
             * </pre>
             *
             * <code>optional string EndorserAddress = 3;</code>
             */
            public Builder clearEndorserAddress() {
                copyOnWrite();
                instance.clearEndorserAddress();
                return this;
            }

            /**
             * <pre>
             * 背书服务地址
             * </pre>
             *
             * <code>optional string EndorserAddress = 3;</code>
             */
            public Builder setEndorserAddressBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setEndorserAddressBytes(value);
                return this;
            }

            /**
             * <pre>
             * 背书服务签名
             * </pre>
             *
             * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
             */
            public boolean hasEndorserSign() {
                return instance.hasEndorserSign();
            }

            /**
             * <pre>
             * 背书服务签名
             * </pre>
             *
             * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
             */
            public com.baidu.xuper.pb.XchainOuterClass.SignatureInfo getEndorserSign() {
                return instance.getEndorserSign();
            }

            /**
             * <pre>
             * 背书服务签名
             * </pre>
             *
             * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
             */
            public Builder setEndorserSign(com.baidu.xuper.pb.XchainOuterClass.SignatureInfo value) {
                copyOnWrite();
                instance.setEndorserSign(value);
                return this;
            }

            /**
             * <pre>
             * 背书服务签名
             * </pre>
             *
             * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
             */
            public Builder setEndorserSign(
                    com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.Builder builderForValue) {
                copyOnWrite();
                instance.setEndorserSign(builderForValue);
                return this;
            }

            /**
             * <pre>
             * 背书服务签名
             * </pre>
             *
             * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
             */
            public Builder mergeEndorserSign(com.baidu.xuper.pb.XchainOuterClass.SignatureInfo value) {
                copyOnWrite();
                instance.mergeEndorserSign(value);
                return this;
            }

            /**
             * <pre>
             * 背书服务签名
             * </pre>
             *
             * <code>optional .pb.SignatureInfo EndorserSign = 4;</code>
             */
            public Builder clearEndorserSign() {
                copyOnWrite();
                instance.clearEndorserSign();
                return this;
            }

            /**
             * <code>optional bytes ResponseData = 5;</code>
             */
            public com.google.protobuf.ByteString getResponseData() {
                return instance.getResponseData();
            }

            /**
             * <code>optional bytes ResponseData = 5;</code>
             */
            public Builder setResponseData(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setResponseData(value);
                return this;
            }

            /**
             * <code>optional bytes ResponseData = 5;</code>
             */
            public Builder clearResponseData() {
                copyOnWrite();
                instance.clearResponseData();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:pb.EndorserResponse)
        }

        protected final Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse other = (com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse) arg1;
                    header_ = visitor.visitMessage(header_, other.header_);
                    responseName_ = visitor.visitString(!responseName_.isEmpty(), responseName_,
                            !other.responseName_.isEmpty(), other.responseName_);
                    endorserAddress_ = visitor.visitString(!endorserAddress_.isEmpty(), endorserAddress_,
                            !other.endorserAddress_.isEmpty(), other.endorserAddress_);
                    endorserSign_ = visitor.visitMessage(endorserSign_, other.endorserSign_);
                    responseData_ = visitor.visitByteString(responseData_ != com.google.protobuf.ByteString.EMPTY, responseData_,
                            other.responseData_ != com.google.protobuf.ByteString.EMPTY, other.responseData_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                            .INSTANCE) {
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!input.skipField(tag)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 10: {
                                    com.baidu.xuper.pb.XchainOuterClass.Header.Builder subBuilder = null;
                                    if (header_ != null) {
                                        subBuilder = header_.toBuilder();
                                    }
                                    header_ = input.readMessage(com.baidu.xuper.pb.XchainOuterClass.Header.parser(), extensionRegistry);
                                    if (subBuilder != null) {
                                        subBuilder.mergeFrom(header_);
                                        header_ = subBuilder.buildPartial();
                                    }

                                    break;
                                }
                                case 18: {
                                    String s = input.readStringRequireUtf8();

                                    responseName_ = s;
                                    break;
                                }
                                case 26: {
                                    String s = input.readStringRequireUtf8();

                                    endorserAddress_ = s;
                                    break;
                                }
                                case 34: {
                                    com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.Builder subBuilder = null;
                                    if (endorserSign_ != null) {
                                        subBuilder = endorserSign_.toBuilder();
                                    }
                                    endorserSign_ = input.readMessage(com.baidu.xuper.pb.XchainOuterClass.SignatureInfo.parser(), extensionRegistry);
                                    if (subBuilder != null) {
                                        subBuilder.mergeFrom(endorserSign_);
                                        endorserSign_ = subBuilder.buildPartial();
                                    }

                                    break;
                                }
                                case 42: {

                                    responseData_ = input.readBytes();
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {
                        synchronized (com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse.class) {
                            if (PARSER == null) {
                                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                            }
                        }
                    }
                    return PARSER;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:pb.EndorserResponse)
        private static final com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new EndorserResponse();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static com.baidu.xuper.pb.XendorserOuterClass.EndorserResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<EndorserResponse> PARSER;

        public static com.google.protobuf.Parser<EndorserResponse> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
